
spring:
  application:
    name: auth-service-eureka-client

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.20.2.41:32643/dockinput_authorization_server?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: abcdefg
    hikari:
      max-lifetime: 500000

server:
  port: 10001
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:10000/eureka/
debug: true