spring:
  application:
    name: auth-client

  security:
    oauth2:
      client:
        registration:
          local_client:
            client-id: local_client_id
            client-secret: 123456
            client-name: local_client_name
            scope: read,write
            authorization-grant-type: authorization_code
            provider: local_oauth2
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            # 认证方法
            client-authentication-method: client_secret_basic

        provider:
          local_oauth2:
            # 请求授权码地址
            authorization-uri: http://os.com:10001/oauth2/authorize
            # 请求令牌地址
            token-uri: http://os.com:10001/oauth2/token
            # 用户资源地址
            user-info-uri: http://os.com:10001/oauth2/user
            # 用户资源返回中的一个属性名
            user-name-attribute: name
            user-info-authentication-method: GET
server:
  port: 10003

